name: Create torrent using py3createtorrent
on:
  push:
    paths:
      - ".github/workflows/py3createtorrent.yml"
      
env:
  name: "Demonslayer"
  comment: "mugentrain"
  url: "https://download1485.mediafire.com/kiwqzsb8pp7g/bu1cb2vmrca2cid/%5BAnime60FPS.com%5DKMUGEN-4K60fps.mkv"
  file_name: "demon slayer mugen train"
  piece_size: 0 # 0 for automatic calculation, or use the recommended piece size on the README.md file
  maximize_disk_space: false # Set to true if out of disk space
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize disk space
        if: ${{ env.maximize_disk_space == 'true' }}
        uses: easimon/maximize-build-space@v4
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
      - name: Install py3createtorrent
        run: sudo pip3 install py3createtorrent
        
      - name: Download file
        run: aria2c -x 16 -o "$file_name" "$url"
        
      - name: Create torrent using py3createtorrent
        run: py3createtorrent -p $piece_size -c "$comment" -o "${name}.torrent" --webseed "$url" "$file_name" # Tested on 1.0.0
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
